module.exports = {
  root: true,
  plugins: ['@typescript-eslint', 'eslint-comments', 'react-hooks'],
  extends: ['react-app', 'react-app/jest', 'plugin:prettier/recommended'],
  rules: {
    'prefer-arrow-callback': 'warn',
    'no-var': 'warn',
    'no-const-assign': 'error',
    'block-scoped-var': 'error',
    'default-case': 'error',
    'handle-callback-err': 'warn',
    'no-path-concat': 'error',
    'no-undef': 'error',
    '@typescript-eslint/no-unused-vars': 'warn',
    'no-unreachable': 'error',
    'no-unused-expressions': 'warn',
    'no-redeclare': 'error',
    'no-debugger': 'off',
    'vars-on-top': 'error',
    'spaced-comment': 'warn',
    strict: 'error',
    'prefer-template': 'warn',
    'prefer-const': 'error',
    'no-useless-concat': 'warn',
    '@typescript-eslint/no-use-before-define': 'error',
    'react/prop-types': 'off',
    '@typescript-eslint/restrict-template-expressions': 'off',
    '@typescript-eslint/no-unsafe-call': 'off',
    '@typescript-eslint/no-floating-promises': 'off',
    '@typescript-eslint/prefer-regexp-exec': 'off',
    'react/display-name': 'off',
    '@typescript-eslint/no-empty-function': 'warn',
    'no-shadow': 'off',
    '@typescript-eslint/no-shadow': ['error'],
    'react/self-closing-comp': [
      'error',
      {
        component: true,
      },
    ],
  },
};
